# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[manager]
show_hidden = true


[opener]
play = [
	{ run = 'mpv "$@"', orphan = true, for = "unix" },
	{ run = '"C:\Program Files\mpv.exe" %*', orphan = true, for = "windows" }
]

edit = [
	{ run = '$EDITOR "$@"', block = true, for = "unix" },
	{ run = 'nvim %*',  block = true, for = "windows" },
]

excel = [
	 { run = 'Start-Process excel "$@"', for = "windows"  },
]




[open]
append_rules = [
	# { name = "*", use = "edit"},
	{ name = "*.xlsx", use = "excel"},
]
